# Generated by Django 4.1.5 on 2023-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
