# Generated by Django 4.1.5 on 2023-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subject', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
