# Generated by Django 4.1.5 on 2023-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teachingclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingclass',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
