# Generated by Django 4.1.5 on 2023-01-11 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_teachingclass_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendannce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teachingclass')),
            ],
        ),
    ]
