# Generated by Django 4.1.5 on 2023-01-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_attendannce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendannce',
            new_name='Attendance',
        ),
    ]
