# Generated by Django 4.1.5 on 2023-01-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_attendannce_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachingClass',
            new_name='Group',
        ),
    ]
