# Generated by Django 4.1.5 on 2023-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachernotepad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attendances',
            field=models.ManyToManyField(through='teachernotepad.Attendance', to='teachernotepad.student'),
        ),
    ]
